def multiples_of_3_and_5(n_: int, _n: int, up_to: int) -> list:
    """Problem 1.


    If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
    The sum of these multiples is 23.
    Find the sum of all the multiples of 3 or 5 below 1000.
    """
    return [x for x in range(1, up_to) if any((not x % n_, not x % _n))]


def even_fibonacci_numbers(n: int) -> int:
    """Problem 2.


    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
    """
    a, b, total = 0, 1, 0
    while b <= n:
        a, b = b, a+b
        if not a % 2:
            total += a
    return total


def largest_prime_factor(n: int) -> int:
    """Problem 3.


    The prime factors of 13195 are 5, 7, 13 and 29.
    What is the largest prime factor of the number 600851475143 ?
    """

    def primes():
        for x in range(2, n):
            for y in range(2, x):
                if not x % y:
                    break
            else:
                yield x

    primes = iter(primes())
    factors = []
    while n != 1:
        factor = next(primes)
        if not n % factor:
            n //= factor
            factors.append(factor)

    return max(factors)


def largest_palindrome_product(n: int) -> int:
    """Problem 4.


    A palindromic number reads the same both ways.
    The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
    Find the largest palindrome made from the product of two 3-digit numbers.
    """
    for i in range(10 ** n - 1, 0, -1):
        for j in range(10 ** n - 1, 0, -1):
            x = i * j
            if str(x) == str(x)[::-1]:
                return x


def smallest_multiple(upto: int) -> int:
    """Problem 5.


    2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
    What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
    """
    numbers = [11, 13, 14, 16, 17, 18, 19, 20]
    for n in range(upto, 10 ** upto - 1, upto):
        if all(not n % x for x in numbers):
            return n


def sum_square_difference(n: int) -> int:
    """Problem 6.
    The sum of the squares of the first ten natural numbers is 1^2+2^2+...+10^2=385,
    The square of the sum of the first ten natural numbers is (1+2+...+10)^2=55^2=3025,
    Hence the difference between the sum of the squares of the first ten
    natural numbers and the square of the sum is 3025-385=2640.
    Find the difference between the sum of the squares of the first one hundred
    natural numbers and the square of the sum.
    """
    from functools import reduce
    from operator import add
    sum_of_square = sum(x ** 2 for x in range(1, n + 1))
    square_of_sum = reduce(add, range(1, n + 1)) ** 2
    return square_of_sum - sum_of_square


def _10001st_prime(n: int) -> int:
    """Problem 7.


    By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
    What is the 10 001st prime number?
    """

    def is_prime(_n):
        if _n < 2:
            return
        for i in range(2, int(_n ** 0.5) + 1):
            if not _n % i:
                return
        return True

    primes = 0
    prime = 1

    while primes < n:
        prime += 1
        if is_prime(prime):
            primes += 1
    return prime


def largest_product_in_series(n: int) -> int:
    """Problem 8.


    The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

    73167176531330624919225119674426574742355349194934
    96983520312774506326239578318016984801869478851843
    85861560789112949495459501737958331952853208805511
    12540698747158523863050715693290963295227443043557
    66896648950445244523161731856403098711121722383113
    62229893423380308135336276614282806444486645238749
    30358907296290491560440772390713810515859307960866
    70172427121883998797908792274921901699720888093776
    65727333001053367881220235421809751254540594752243
    52584907711670556013604839586446706324415722155397
    53697817977846174064955149290862569321978468622482
    83972241375657056057490261407972968652414535100474
    82166370484403199890008895243450658541227588666881
    16427171479924442928230863465674813919123162824586
    17866458359124566529476545682848912883142607690042
    24219022671055626321111109370544217506941658960408
    07198403850962455444362981230987879927244284909188
    84580156166097919133875499200524063689912560717606
    05886116467109405077541002256983155200055935729725
    71636269561882670428252483600823257530420752963450

    Find the thirteen adjacent digits in the 1000-digit number that have the greatest product.
    What is the value of this product?
    """
    series = """
            73167176531330624919225119674426574742355349194934
            96983520312774506326239578318016984801869478851843
            85861560789112949495459501737958331952853208805511
            12540698747158523863050715693290963295227443043557
            66896648950445244523161731856403098711121722383113
            62229893423380308135336276614282806444486645238749
            30358907296290491560440772390713810515859307960866
            70172427121883998797908792274921901699720888093776
            65727333001053367881220235421809751254540594752243
            52584907711670556013604839586446706324415722155397
            53697817977846174064955149290862569321978468622482
            83972241375657056057490261407972968652414535100474
            82166370484403199890008895243450658541227588666881
            16427171479924442928230863465674813919123162824586
            17866458359124566529476545682848912883142607690042
            24219022671055626321111109370544217506941658960408
            07198403850962455444362981230987879927244284909188
            84580156166097919133875499200524063689912560717606
            05886116467109405077541002256983155200055935729725
            71636269561882670428252483600823257530420752963450""".replace('\n', '').replace(' ', '')
    max_product = 0
    from functools import reduce
    from operator import mul

    for index, product in enumerate(series):
        product = series[index: index + n]
        n_product = reduce(mul, map(int, product))
        if n_product > max_product:
            max_product = n_product
    return max_product


def special_pythagorean_triplet(n: int) -> tuple:
    """Problem 9.


    A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
    a^2 + b^2 = c^2
    For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.
    There exists exactly one Pythagorean triplet for which a + b + c = 1000.
    Find the product abc.
    """
    for a in range(n):
        for b in range(1, n):
            for c in range(b, n - b):
                if a + b + c == n and a ** 2 + b ** 2 == c ** 2:
                    return a, b, c


def summation_of_primes(n: int) -> int:
    """Problem 10.


    The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
    Find the sum of all the primes below two million.
    """
    return sum(x for x in range(2, n + 1) if not n % x)

# print(multiples_of_3_and_5(3, 5, 1000))
# print(even_fibonacci_numbers(int(4e6)))
# print(largest_prime_factor(600851475143))
# print(largest_palindrome_product(3))
# print(smallest_multiple(20))
# print(sum_square_difference(100))
# print(_10001st_prime(10001))
# print(largest_product_in_series(14))
# print(special_pythagorean_triplet(1000))
# print(summation_of_primes(int(2e6)))
